### ISSUE TITLE
Stacktrace, wenn Command aus deaktiviertem Plugin ausgeführt wird

### ISSUE THREAD

**Issue by Archerymaister** [Cube-Nation/Bedrock#32]
Wenn ein Command aus einem Plugin das beim Serverstart durch einen Fehler deaktiviert wurde gestartet wird, kommt ein Stacktrace. Reicht da nicht auch eine einfache Meldung die das abfängt?

```
> macro delete
[21:29:46 WARN]: Unexpected exception while parsing console command "macro delete"
org.bukkit.command.CommandException: Cannot execute command 'macro' in plugin CNMacro v1.1.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.17.1.jar:git-Paper-233]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-233]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-233]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-233]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-233]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Kronnox** [comment]
Ist befürchte ich Bukkit Command Handling und nichts von Bedrock. Sofern wir uns da nicht komplett von Bukkit lösen, können wir da vermutlich nichts machen :/
